### ISSUE TITLE
Gstreamer server getting stuck while display "Audio sent, now sending EOS" message

### ISSUE THREAD

**Issue by Habush** [jcsilva/docker-kaldi-gstreamer-server#12]
I have trained Amharic model which I want to use for speech recognition. I was able to successfully setup the kaldi-gstreamer server by following the instruction in the **README** file. However, when I try to get text transcribtion, it gets stuck by display the message **"Audio sent, now sending EOS"**. I waited for several hours and still it is not showing anything change. So I stopped it forcefully. What is going wrong here?

Here is the command I ran:
    _python /tmp/client.py -u ws://localhost:8181/client/ws/speech -r 32768 /tmp/amh_test.wav_

**Comment by jcsilva** [comment]
Hi,

first of all, your "byte rate" seems a bit strange. You set 32768?
Shouldn't it be something like 32000 (16000 khz * 2 bytes/sample) ?

Also, I do recommend you to go inside the docker container and check
/opt/worker.log file. It may give you some hints about your problem.
You may do it following these steps:

1) docker ps -a: you will see a list of containers and you will see the
reference for the container you are running your server.
2) docker exec -it <reference_id> /bin/bash: this will allow you to "enter
in" your containter.
3) cat /opt/worker.log

I think it may help you!

2016-12-26 16:36 GMT-02:00 Abdulrahman Semrie <notifications@github.com>:

**Comment by Habush** [comment]
You're right the byte rate is odd. I (wrongly) thought it was calculated from bit rate and the audio has a bit rate of 256kbps (256*1024/8). However, I had previously tried with value of 32000 with no luck

As to the worker log, I have attached it so that you could take a look at it. Honestly, I couldn't see any errors that would point me to a solution. (I have changed its extension .txt as github doesn't support files with .log files)
[worker.txt](https://github.com/jcsilva/docker-kaldi-gstreamer-server/files/673355/worker.txt)

**Comment by jcsilva** [comment]
I saw you had some errors when trying to decode your audio. The logged
message was:

*ERROR: SymbolTable::ReadText: Bad non-negative integer "nonword", file =
/opt/models/amh_asr/word_boundary.txt, line = 1*

I think you are using a wrong "words.txt" file. Please, check the
*word-syms* entry in your .yaml file is right.
The words-syms must point to a file composed by 2 columns like these:


*<eps> 0*
*o 1*
*galo 2*


2016-12-26 20:52 GMT-02:00 Abdulrahman Semrie <notifications@github.com>:

**Comment by Habush** [comment]
I followed your suggestion and replaced the **words.txt** file with one that resembles your example. However, when I run the **client.py** script, it doesn't display anything. When I look into the **worker.log** file, I found the error to be the following:
     

>   ERROR (OnlineLdaInput():online-feat-input.cc:209) Invalid parameters supplied to OnlineLdaInput
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  ERROR (OnlineLdaInput():online-feat-input.cc:209) Invalid parameters supplied to OnlineLdaInput
> 
> [stack trace: ]
> kaldi::KaldiGetStackTrace()
> kaldi::KaldiErrorMessage::~KaldiErrorMessage()
> kaldi::OnlineLdaInput::OnlineLdaInput(kaldi::OnlineFeatInputItf*, kaldi::Matrix<float> const&, int, int)
> /opt/kaldi/src/gst-plugin/libgstkaldi.so(+0x13301) [0x7f63da1de301]
> /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x94ad6) [0x7f63dc3d4ad6]
> /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x712c8) [0x7f63ddf072c8]
> /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x70935) [0x7f63ddf06935]
> /lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7f63e01c30a4]
> /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f63df5d504d]
> 
> 

What could be going wrong? I have uploaded both the **words.txt** and **worker.log** files incase you want to look into them.
[words.txt](https://github.com/jcsilva/docker-kaldi-gstreamer-server/files/692304/words.txt)
[worker.log.txt](https://github.com/jcsilva/docker-kaldi-gstreamer-server/files/692305/worker.log.txt)

**Comment by jcsilva** [comment]
Hi,

your words.txt seems fine. 

Now you're facing problems with your acoustic model. You have changed it since your first message? When you reported your first problem, I though you didn't have this problem.

And the problem you reported now seems to be caused because you didn't tell the context you used when training your acoustic model. If it is different from 4, you must tell it in your yaml file. For example, if it is 3, you should say:

timeout-decoder : 10
decoder:
   model: <your final.mdl>
   lda-mat: <your final.mat>
   word-syms: <your words.txt>
   fst: <your HCLG.fst>
   silence-phones: <your silence phones>
   **left-context: 3
   right-context: 3**
out-dir: tmp
and so on...

**Comment by Habush** [comment]
Thank you very much! It is working properly now.
