### ISSUE TITLE
Is there any solution for the low quality audio?

### ISSUE THREAD

**Issue by wang850228803** [jcsilva/docker-kaldi-gstreamer-server#13]
Is there any solution for the low quality audio?

**Comment by jcsilva** [comment]
I didn't get what do you mean by low quality audio. Could you please be a bit more specific? And could you provide some examples?

**Comment by wang850228803** [comment]
This is an example.

[description09.aac.zip](https://github.com/jcsilva/docker-kaldi-gstreamer-server/files/718283/description09.aac.zip)

**Comment by jcsilva** [comment]
Well, 

you do have some problems with this sample. 

1)It seems to be encoded/decoded by some low bitrate codec. This codec introduces some distortions and I think that if your acoustic model was not trained with some similar distortion you will have poor transcriptions.

2) Even though your data was sampled at 48000 Hz, your spectrogram shows a bandwith of just 6 ~7 kHz. I think it was done by your codec. The problem again is that if your acoustic model was not trained using the similar "low quality audio", you will have problems in your transcriptions
