### ISSUE TITLE
Any news on PT-BR recognition?

### ISSUE THREAD

**Issue by Vitorbnc** [jcsilva/docker-kaldi-gstreamer-server#14]
Hello,
I'm from Brazil too and wanted to build voice interfaces that worked offline for robots in Portuguese. However, I couldn't find any good solution that works offline and continuously. So, I'd like to know if there's any news or links for a Brazilian Portuguese model.

**Comment by jcsilva** [comment]
Hi Vítor,

until now I don't have any news for a kaldi-based Brazilian Portuguese model. I keep working on it, but without too much success until now.

Another thing ... your project sounds interesting. Could you please tell more about it? You can e-mail me if you prefer and it can be in Portuguese :).

**Comment by Vitorbnc** [comment]
Bom dia! Não encontrei seu email aqui no github, mas o projeto é um mini carro autônomo com Rasberry Pi, mais pra aprendizado mesmo. O hardware está pronto, mas falta fazer o software, a ideia é usar CV com a câmera e comandar ele com linguagem natural. No meu tempo livre, pretendo continuar.
