### ISSUE TITLE
Error trying to build docker image

### ISSUE THREAD

**Issue by ribeirogustavoti** [jcsilva/docker-kaldi-gstreamer-server#16]
Got an error trying to build the docker image for practical-example.

Linux hostname 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Command ran:**
docker build -t docker-kaldi-gstreamer-example:latest .

**Error log:**
Sending build context to Docker daemon 728.5 MB
Step 1/5 : RUN mkdir -p /opt/models && cd /opt/models &&     wget https://phon.ioc.ee/~tanela/tedlium_nnet_ms_sp_online.tgz &&     tar -zxvf tedlium_nnet_ms_sp_online.tgz &&     wget https://raw.githubusercontent.com/alumae/kaldi-gstreamer-server/master/sample_english_nnet2.yaml -P /opt/models &&     find /opt/models/ -type f | xargs sed -i 's:test:/opt:g' &&     sed -i 's:full-post-processor:#full-post-processor:g' /opt/models/sample_english_nnet2.yaml
Please provide a source image with `from` prior to run
[gfsitman@sv003-sp-itman01 ~]$ docker run -itd -p 8080:80 --shm-size=256m  docker-kaldi-gstreamer-example:latest
Unable to find image 'docker-kaldi-gstreamer-example:latest' locally
docker: Error response from daemon: repository docker-kaldi-gstreamer-example not found: does not exist or no pull access.
See 'docker run --help'.

**Comment by jcsilva** [comment]
Something seems weird in your execution. You showed 1/5 steps. But it should execute 7 steps.

You should have something like:
docker build -t docker-kaldi-gstreamer-example:latest .
Sending build context to Docker daemon 728.5 MB
Step 1/7 : FROM jcsilva/docker-kaldi-gstreamer-server
...

Are you sure that you copied the entire Dockerfile? You must copy the header, specially the FROM command.
