### ISSUE TITLE
How long until docker build image updated on hub.docker.com

### ISSUE THREAD

**Issue by mike-a-ellis** [jcsilva/docker-kaldi-gstreamer-server#25]
Any idea how long until the docker image file from docker hub is updated to include Python 3?  I tried to use it and ran into problems...was wondering if that was why.

PS Your work is awesome!

**Comment by jcsilva** [comment]
Hi,

I'm trying to build a new docker image these days. Probably, next week it
will be available.

Thanks for you comment!

2017-10-04 14:47 GMT-03:00 bulltorious <notifications@github.com>:

**Comment by jcsilva** [comment]
Hi,

the new docker image was uploaded to docker hub a couple of weeks ago. I forgot to update you... sorry. 
But it's is there. If you find any error, please let me know.

**Comment by mike-a-ellis** [comment]
Thanks man !  Keep up the great work.
