### ISSUE TITLE
No decoder available, try again later

### ISSUE THREAD

**Issue by soixantseize** [jcsilva/docker-kaldi-gstreamer-server#3]
Hello, thank you for this project.  I am having a problem with the Practical Example.  I instantiated the server worker on the same machine and I then started the service.  However, every time I invoke python /tmp/client.py -u ws://localhost:8080/client/ws/speech -r 32000 /tmp/1272-128104-0000.wav ; I get the error message No decoder available, try again later.  Can you help me getting the example to work?

**Comment by jcsilva** [comment]
Could you please show me the .yaml file that you are using?

**Comment by soixantseize** [comment]
I used the .yaml from Step #2 in the Practical Example (https://raw.githubusercontent.com/alumae/kaldi-gstreamer-server/master/sample_english_nnet2.yaml)

**Comment by jcsilva** [comment]
Could you please start the service using the attached yaml file? (Inside the container, you should run: /opt/start.sh -y /opt/models/modified.yaml.txt)

If you have more problems, please send me the file /opt/master.log and /opt/worker.log

[modified.yaml.txt](https://github.com/jcsilva/docker-kaldi-gstreamer-server/files/148948/modified.yaml.txt)

**Comment by soixantseize** [comment]
It is now working!!!!  Thank you very much.  I think the problem was due to having only 2G of RAM in my virtual machine.  After I bumped it up to 4G it started working. Thanks again.

**Comment by jcsilva** [comment]
You are welcome! And thanks for your feedback!
I'm going to update the README, warning about memory issues!

This Issue may be closed?

**Comment by h770347** [comment]
> It is now working!!!! Thank you very much. I think the problem was due to having only 2G of RAM in my virtual machine. After I bumped it up to 4G it started working. Thanks again.

How What is the code please!
