### ISSUE TITLE
ImportError: No module named ws4py.client.threadedclient

### ISSUE THREAD

**Issue by xiaotingFu** [jcsilva/docker-kaldi-gstreamer-server#35]
Hi I was trying to running the example script, I have docker installed correctly and running the 
"jcsilva/docker-kaldi-gstreamer-server:latest" image 

$ docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                  NAMES
1b14dcb974c8        jcsilva/docker-kaldi-gstreamer-server:latest   "/bin/bash"              3 minutes ago       Up 3 minutes        0.0.0.0:8081->80/tcp   clever_spence

I also run the following command inside the docker image:
root@1b14dcb974c8:/opt# /opt/start.sh -y /opt/models/sample_english_nnet2.yaml

While I am trying to test the web client in my Host OS (Mac OS X) with these scripts:
wget https://raw.githubusercontent.com/alumae/kaldi-gstreamer-server/master/kaldigstserver/client.py -P /tmp
wget https://raw.githubusercontent.com/jcsilva/docker-kaldi-gstreamer-server/master/audio/1272-128104-0000.wav -P /tmp
wget https://raw.githubusercontent.com/alumae/kaldi-gstreamer-server/master/test/data/bill_gates-TED.mp3 -P /tmp

python /tmp/client.py -u ws://localhost:8081/client/ws/speech -r 32000 /tmp/1272-128104-0000.wav
python /tmp/client.py -u ws://localhost:8081/client/ws/speech -r 8192 /tmp/bill_gates-TED.mp3

However,
The following problem appears:
$ python /tmp/client.py -u ws://localhost:8080/client/ws/speech -r 8192 /tmp/bill_gates-TED.mp3
Traceback (most recent call last):
  File "/tmp/client.py", line 4, in <module>
    from ws4py.client.threadedclient import WebSocketClient
ImportError: No module named ws4py.client.threadedclient
cei-mac02:~ xiaotingfu$ python /tmp/client.py -u ws://localhost:8081/client/ws/speech -r 8192 /tmp/bill_gates-TED.mp3
Traceback (most recent call last):
  File "/tmp/client.py", line 4, in <module>
    from ws4py.client.threadedclient import WebSocketClient
ImportError: No module named ws4py.client.threadedclient

（I also install ws4py as instructed)
$ pip install --user ws4py==0.3.2
Requirement already satisfied: ws4py==0.3.2 in ./Library/Python/3.6/lib/python/site-packages (0.3.2)

Can you help me with that? Do you think is that because my pip is connected to python3?

**Comment by jcsilva** [comment]
Yes, I think the problem is because you are using python3. Could you please test it with python 2?

**Comment by xiaotingFu** [comment]
Thanks for your quick reply, my issue is solved!
I have two different Python installed in my Mac, and the default pip command is connected to python3.

After I uninstall python3 and reinstall pip, the problem is solved!

**Comment by xiaotingFu** [comment]
However, after that I encounter another issue which related to remote access using SSH.

Whenever I issue the command:
`$ python /tmp/client.py -u ws://localhost:8080/client/ws/speech -r 8192 /tmp/bill_gates-TED.mp3`
An error message says
`Connection refused` come up. 
I solved it by using a local computer.
It's because I am SSH into another machine and the connected is refused if you are requesting through SSH.
