### ISSUE TITLE
trouble getting to solve worker.log file in kaldi with docker and gstreamer

### ISSUE THREAD

**Issue by Vishnu-Chittan** [jcsilva/docker-kaldi-gstreamer-server#49]
Dear jcsilva
Greetings ......
                      Currently, I am working on KALDI with docker and gstreamer. I am following your's repository and " https://medium.com/@nikhilamunipalli/simple-guide-to-kaldi-an-efficient-open-source-speech-recognition-tool-for-extreme-beginners-98a48bb34756"  this link.
                   after running " ./start.sh -y opt/models/nnet2.yaml " command, I am checking the worker.log
[worker.log](https://github.com/jcsilva/docker-kaldi-gstreamer-server/files/2709584/worker.log)
 file. There I am getting some errors. Here I am attaching the worker.log file too. Kindly guide me in this regard.

**Comment by jcsilva** [comment]
already addressed at #8

**Comment by Vishnu-Chittan** [comment]
Thank you so much for your reply...
