### ISSUE TITLE
How would I start multiple workers and connect them to a master?

### ISSUE THREAD

**Issue by DaniilHarik** [jcsilva/docker-kaldi-gstreamer-server#5]
Hello,

How would I start multiple workers and connect them to a single master?

I've tried adding multiple worker start lines to the start.sh, but it does not seem to work

`python /opt/kaldi-gstreamer-server/kaldigstserver/worker.py -c $YAML -u ws://$MASTER:$PORT/worker/ws/speech 2>> /opt/worker.log &`

Thank You

**Comment by jcsilva** [comment]
Hi, 

you may use the script "start.sh" multiple times to connect many workers to a single master. 

For example, imagine you have a master server with ip address 10.0.0.13, port 8080.
For connecting 2 workers to this master, you should do

$ start.sh -y <yamlfile1> -m 10.0.0.13 -p 8080
$ start.sh -y <yalmfile2> -m 10.0.0.13 -p 8080

I always used one worker per machine and I know it works. So, in this example I mentioned, you should use 2 different machines.
